### ISSUE TITLE
'/home/runner/svn-{plugin-slug}/tags/refs/heads' is not a directory after auto create release

### ISSUE THREAD

**Issue by 0xBeycan** [helen/action-wordpress-plugin-deploy#142]
Hello, if I set the trigger to release:published, it will not trigger after the automatic release. However, if I run it after the automatic release workflow is completed, I get the following error.

'/home/runner/svn-{plugin-slug}/tags/refs/heads' is not a directory

**Comment by jeffpaul** [comment]
@BeycanDeveloper do you have a link to an action run(s) so we can help triage a bit further?

**Comment by 0xBeycan** [comment]
I don't have but i will explain to you. 

I have two workflow
1 - Publish to WP -> events = release, workflow_run
2 - Create auto release -> events = push (with version format commit message)

If i create manual release everyting working good

but

If i sent like that commit "1.6.9" creating auto release with github bot and later trigger workflow 1 so publish to wp and this time giving this error

**Comment by jeffpaul** [comment]
@BeycanDeveloper I appreciate the additional info, but I'm still not clear on where you're looking to utilize this GitHub Action and how its failing.  Any chance you can share a bit more detail / screenshots / screencasts to better highlight your issue/concern?

**Comment by KevinBatdorf** [comment]
Maybe related to second half, if the target on a release looks like this it will error

![CleanShot 2024-01-02 at 21 25 51@2x](https://github.com/10up/action-wordpress-plugin-deploy/assets/1478421/ebdb6737-30a7-4d5f-a236-c398c27690a0)

**Comment by 0xBeycan** [comment]
@KevinBatdorf if i crate manually don't have any problem. But i think this interest with event.

Because if working on event release:published working good
But if working on event workflow_run:completed giving this error

I am adding my worklows below

```
name: Create auto release

on: 
  push:
    branches:
      - master

jobs:
  auto_release:
    name: Auto release
    permissions: write-all
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Extract version from commit message
      id: extract_version
      run: |
        VERSION=$(git log --format=%B -n 1 ${{ github.sha }} | grep -o -E '[0-9]+\.[0-9]+\.[0-9]+' || true)
        if [ -z "$VERSION" ]; then
          exit 1
        fi
        echo "::set-output name=version::$VERSION"

    - name: Create Release
      id: create_release
      if: steps.extract_version.outputs.version
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.extract_version.outputs.version }}
        release_name: Version ${{ steps.extract_version.outputs.version }}
        body: Version ${{ steps.extract_version.outputs.version }}
        draft: false
        prerelease: false
```

In below event, if trigerred with release everything good, but if triggered with workflow run giving this error

```
name: Publish to WordPress.org

on:
  workflow_run:
    workflows: ["Create auto release"]
    branches:
      - alpha
      - master
    types:
      - completed
  release:
    types:
      - published
    branches:
      - master

env:
  PLUGIN_SLUG: cryptocurrency-payments-for-paid-memberships-pro

jobs:
  deploy_to_wp_org:
    permissions: write-all
    name: WordPress.org Plugin Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_PASSWORD: ${{ secrets.WORDPRESS_ORG_PASSWORD }}
        SVN_USERNAME: ${{ secrets.WORDPRESS_ORG_USERNAME }}
        SLUG: ${{ env.PLUGIN_SLUG }}
    
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.deploy.outputs.zip-path }}
        asset_name: ${{ env.PLUGIN_SLUG }}.zip
        asset_content_type: application/zip
```

i think this enough clearly but i don't know how can i explane more
