### ISSUE TITLE
ubuntu-latest lo longer comes with SVN installed

### ISSUE THREAD

**Issue by tobeyadr** [helen/action-wordpress-plugin-deploy#151]
**Describe the bug**
[ubuntu-latest](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) no longer has SVN installed, meaning example files will not function as expected.

**Steps to Reproduce**
Use ubuntu-latest in your .yml and you'll see "svn: command not found"

**Expected behavior**
The plugin should be deployed to SVN.

**Additional context**
Please recommend that authors use "ubuntu-22.04" instead in your example files.

**Comment by helen** [comment]
For future-proofing it's probably not best to stay on an old OS, a more correct route would be to [install subversion as a step](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/customizing-github-hosted-runners) which is actually what used to happen before this became a composite action running directly on the runner instead for speed, see https://github.com/10up/action-wordpress-plugin-deploy/commit/8926c88630933b95c9ddf9279f95dc9176447eae (you'll need to load the contents of the deleted `Dockerfile`)

**Comment by fumikito** [comment]
F.Y.I

Same for me, and adding this step works fine :)

```yml
      - name: Install Subversion
        run: sudo apt-get install subversion

      - name: Deploy to WordPress Directory
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.WP_ORG_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WP_ORG_PASSWORD }}
```
