### ISSUE TITLE
svn: command not found

### ISSUE THREAD

**Issue by Surbma** [helen/action-wordpress-plugin-deploy#158]
Hi,

I was using the `master` branch previously, but wanted to use the latest version of this action. So I have changed the configuration to use the `stable` instead of the `master` branch.

Now I'm getting this error every time, when the action is running:
`/home/runner/work/_actions/10up/action-wordpress-plugin-deploy/stable/deploy.sh: line 63: svn: command not found`

I have tried everything, but it seems, it is not working anymore. Can someone help me to find out, where is the problem?

This is the repo, where I need help:
https://github.com/Surbma/surbma-salesautopilot-shortcode

**Comment by michael-sumner** [comment]
@Surbma see https://github.com/10up/action-wordpress-plugin-deploy/issues/157#issuecomment-2555171600

You will need to install the `subversion` command within your .yml file. This is because ubuntu-latest no longer has subversion shipped with it.

I have also added a fix to my plugin repo here if you wish to copy it. Note: that you will need to remove your previous tag, add the `subversion` command, and re-run the action again so that the build release will know to use the subversion command:
https://github.com/scoredetect/timestamps/commit/78440eb194c27ed4812aeaab115f4fdd31e993ec

**Comment by michael-sumner** [comment]
@Surbma see https://github.com/10up/action-wordpress-plugin-deploy/issues/157#issuecomment-2555171600

You will need to install the `subversion` command within your .yml file. This is because ubuntu-latest no longer has subversion shipped with it.

I have also added a fix to my plugin repo here if you wish to copy it. Note: that you will need to remove your previous tag, add the `subversion` command, and re-run the action again so that the build release will know to use the subversion command:
https://github.com/scoredetect/timestamps/commit/78440eb194c27ed4812aeaab115f4fdd31e993ec

**Comment by Surbma** [comment]
Thank you for all the help, I was able to fix it.

This is the final code after a deep investigation:

```
name: Deploy new release to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag is pushed
    runs-on: ubuntu-latest
    steps:
    - name: Install Subversion
      run: sudo apt-get update && sudo apt-get install -y subversion
    - name: Checkout code
      uses: actions/checkout@v3
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
```
