### ISSUE TITLE
is /vendor folder being deleted by the action?

### ISSUE THREAD

**Issue by cristiano-federico-jump** [helen/action-wordpress-plugin-deploy#168]
Hi,
I'm using the 10up/action-wordpress-plugin-deploy action to deploy a plugin to the WordPress SVN repository.

I confirmed that:

- composer install --no-dev runs correctly before deploy
- vendor/ is present at the repository root before the deploy step
- There is no .distignore file in my repository
- Running ls -la vendor and find . -type f in the workflow shows that vendor/autoload.php exists before deploy

However, the vendor/ directory does not appear in the SVN repository after deployment.

```
This is my workflow

name: Deploy to WordPress SVN

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy Plugin to WordPress SVN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Version from Tag
        run: echo "PLUGIN_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Debug Version
        run: echo "Deploying version $PLUGIN_VERSION"

      - name: List vendor directory
        run: ls -la vendor

      - name: Validate SemVer Tag
        run: |
          if [[ ! "$PLUGIN_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(--[a-zA-Z0-9._-]+)?$ ]]; then
            echo "❌ Invalid tag format: $PLUGIN_VERSION"
            exit 1
          fi
          echo "✅ Valid SemVer tag: $PLUGIN_VERSION"

      # - name: Update Version in Files (Temporary)
      #   run: |
      #     sed -i "s/^Stable tag: .*/Stable tag: $PLUGIN_VERSION/" readme.md
      #     sed -i "s/^Stable tag: .*/Stable tag: $PLUGIN_VERSION/" avacy.php
      #     sed -i "s/^Version: .*/Version: $PLUGIN_VERSION/" avacy.php

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@2.3.0
        env:
          SLUG: avacy
          VERSION: ${{ env.PLUGIN_VERSION }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
```

I also tried to copy the vendor folder into another folder named **test** just for testing:

```
- name: Run Composer Install
        run: composer install --no-dev --no-scripts --prefer-dist --optimize-autoloader

- name: Copy vendor directory
        run: cp -R vendor/ test/
```

And it turned out that the test folder was actually deployed in the Wordpress repository.

Is there any reason vendor/ might be silently excluded from the deploy even though it is present and not listed in any .distignore?

Thanks in advance!

**Comment by dkotter** [comment]
So we don't delete any files or folders ourselves, we look at `.distignore` or `.gitattributes` file and use that for what shouldn't be synced (if you're interested, can see how that works here https://github.com/10up/action-wordpress-plugin-deploy/blob/develop/deploy.sh#L129).

You mention:

> There is no .distignore file in my repository

In this case, we fallback to using the `.gitattributes` file. Does this exist in your repo? If not, we end up creating a basic one which will also consider your `.gitignore` file. See https://github.com/10up/action-wordpress-plugin-deploy?tab=readme-ov-file#excluding-files-from-deployment for more information on this but if you have files or folders that are excluded by `.gitignore` but these are things you want deployed, best way to achieve this is adding a `.distignore` file to ensure these files/folders aren't excluded.

Here's an [example `.distignore`](https://github.com/10up/restricted-site-access/blob/develop/.distignore) file from one of our plugins that does need the `vendor` directory deployed and this works.

**Comment by cristiano-federico-jump** [comment]
> So we don't delete any files or folders ourselves, we look at `.distignore` or `.gitattributes` file and use that for what shouldn't be synced (if you're interested, can see how that works here https://github.com/10up/action-wordpress-plugin-deploy/blob/develop/deploy.sh#L129).
> 
> You mention:
> 
> > There is no .distignore file in my repository
> 
> In this case, we fallback to using the `.gitattributes` file. Does this exist in your repo? If not, we end up creating a basic one which will also consider your `.gitignore` file. See https://github.com/10up/action-wordpress-plugin-deploy?tab=readme-ov-file#excluding-files-from-deployment for more information on this but if you have files or folders that are excluded by `.gitignore` but these are things you want deployed, best way to achieve this is adding a `.distignore` file to ensure these files/folders aren't excluded.
> 
> Here's an example `.distignore` file from one of our plugins that does need the `vendor` directory deployed and this works.

Hi @dkotter thanks for the reply!
If I understood correctly a new `.gitattributes` file is created by the action (i don't have that file in the repository) and if my `.gitignore` contains `/vendor` the rule is automatically applied to the `.gitattributes` file, hence removing the vendor folder from the final package.

Is there any way I can add the vendor folder to the package? Should I create a new .gitattributes file where I specify all the gitignore rules except for the vendor?

Thanks again!

**Comment by cristiano-federico-jump** [comment]
> So we don't delete any files or folders ourselves, we look at `.distignore` or `.gitattributes` file and use that for what shouldn't be synced (if you're interested, can see how that works here https://github.com/10up/action-wordpress-plugin-deploy/blob/develop/deploy.sh#L129).
> 
> You mention:
> 
> > There is no .distignore file in my repository
> 
> In this case, we fallback to using the `.gitattributes` file. Does this exist in your repo? If not, we end up creating a basic one which will also consider your `.gitignore` file. See https://github.com/10up/action-wordpress-plugin-deploy?tab=readme-ov-file#excluding-files-from-deployment for more information on this but if you have files or folders that are excluded by `.gitignore` but these are things you want deployed, best way to achieve this is adding a `.distignore` file to ensure these files/folders aren't excluded.
> 
> Here's an example `.distignore` file from one of our plugins that does need the `vendor` directory deployed and this works.

Hi @dkotter, thanks for the reply!
If I understood correctly, the `.gitattributes` file is created by the action (since I don't have any `.gitattributes` file in my repo) based on my `.gitignore` (where the `vendor/` folder rule actually exists), hence removing the folder from the final package.

We tried to add `.distignore` file copying all the rules in the `.gitignore` and removing the vendor folder but the folder is still missing. Am I doing something wrong?

This is my .distignore
```
wp/*
build/*
.env

// other project folders...

.git
.github
.distignore
.gitignore
```

Could you provide the `.distignore` example you mentioned in the previous comment? Don't see any link and I'm not sure if there was supposed to be one in your comment.

Thanks again!

**Comment by dkotter** [comment]
Ah, sorry, meant to copy/paste the link to the `.distignore` file but looks like I missed that. Here's what I was referencing as an example: https://github.com/10up/restricted-site-access/blob/develop/.distignore

> If I understood correctly, the .gitattributes file is created by the action (since I don't have any .gitattributes file in my repo) based on my .gitignore (where the vendor/ folder rule actually exists), hence removing the folder from the final package.

So this isn't exactly correctly but close. Here's how it works:

1. If you have `BUILD_DIR` set, we copy all files from that directory and don't consider `.distignore` or `.gitattributes`
2. Otherwise if you have a `.distignore`, we ignore all files and directories that are in that when running our `rsync` command
3. If you don't have either of those but you do have a `.gitattributes` file, that will be used when we run `git archive`. That command will also consider your `.gitignore` file
4. If none of the above conditions are met, we then create a basic `.gitattributes` file that ignores a few files and then that will be used when we run `git archive`, which again, will also consider your `.gitignore` file

**Comment by cristiano-federico-jump** [comment]
Hello, I tried using BUILD_DIR in my workflow as shown in the code:

```
- name: Prepare build directory
        run: |
          mkdir build
          rsync -av --exclude=build --exclude=.git --exclude=.github --exclude=node_modules ./ build/

- name: Install PHP dependencies in build
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader --working-dir=build
          ls -la build/vendor

- name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@2.3.0
        env:
          SLUG: avacy
          VERSION: ${{ env.PLUGIN_VERSION }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          BUILD_DIR: build
```

but still no vendor folder inside the final package.

Would it be a good idea to run `composer install --no-dev...` in the local environment and commit the generated files inside the repository? I'm aware it might not be the best practice but I can't figure out where the problem is.

Thanks again!
