### ISSUE TITLE
Help wanted: How to run composer install during the deploy process?

### ISSUE THREAD

**Issue by Luc45** [helen/action-wordpress-plugin-deploy#35]
**Describe your question**
I have a plugin that uses a PSR-4 autoloader. Currently, I have the `vendor` folder unignored and committed to the repo.

I would like, however, to be able to ignore the `vendor` folder and adjust the deploy process to run `composer install --no-dev` before actually packaging the ZIP to be sent to WordPress.org.

Problem is, I'm not sure how to accomplish this. Can you help me?

This is my workflows folder, for reference: https://github.com/Luc45/WooCommerce-Correios-Calculo-de-Frete-na-Pagina-do-Produto/tree/master/.github/workflows

Thank you!

**Comment by Luc45** [comment]
I think I got it. I still didn't do an actual release to test it though. Feedbacks are welcome!

```yml
name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      # Clone the repo
      - uses: actions/checkout@master
      # Prepare the release
      - run: ls
      - run: "composer install --no-dev"
      - run: "rm codeception.dist.yml && rm readme.md && rm -rf tests && rm composer.json && rm composer.lock"
      - run: ls
      # Release to WordPress.org
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@1.4.0
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: woo-correios-calculo-de-frete-na-pagina-do-produto
```

**Comment by helen** [comment]
Hi! Yes, you can use direct `run` steps in your workflow file, and you can also collapse it into one step with multiple lines by starting with a `|`. You can see an example here: https://github.com/10up/autoshare-for-twitter/blob/develop/.github/workflows/deploy-to-wpdotorg.yml#L13

In your case, you shouldn't need the step with the `rm` bits because this Action will respect the `.distignore` file you have. Let me know if it doesn't work for you!

**Comment by Luc45** [comment]
Thanks the pipe | tip is nice! I've just tried it out and there's a downside that the output of all commands shows up as a single string in Actions, where with individual "run" commands I get an accordion for each output. It works the same, but it's a bit harder to see:

Pipes:
```yml
      - run: |
          ls
          composer install --no-dev
          ls
          rm codeception.dist.yml && rm readme.md && rm -rf tests && rm composer.json && rm composer.lock
          ls
```
![image](https://user-images.githubusercontent.com/9341686/79940887-5a3a6480-8439-11ea-9935-7b69afe354af.png)

Individual:
```yml
      - run: ls
      - run: "composer install --no-dev"
      - run: ls
      - run: "rm codeception.dist.yml && rm readme.md && rm -rf tests && rm composer.json && rm composer.lock"
      - run: ls
```
![image](https://user-images.githubusercontent.com/9341686/79940988-9d94d300-8439-11ea-819f-2f98308de142.png)

I'm glad there's a better solution than my ugly `rm`'s, I'll definitely try using `.distignore`! Thank you!
