### ISSUE TITLE
No zip file created

### ISSUE THREAD

**Issue by the-csaba** [helen/action-wordpress-plugin-deploy#52]
**Describe the bug**
No zip file created with `generate-zip: true` setting.

**Steps to Reproduce**
1. Configure an action with a subsequent action that awaits for the generated artifacts
2. Let Github run the action
3. Asset action fial with `##[error]Not Found`

**Expected behavior**
The asset action can grab access to the generated zip file. 

**Additional context**
I only tested with a simple plugin without build script Mentioning here because there is a vague description of zip file creation without build script in the [README](https://github.com/10up/action-wordpress-plugin-deploy#excluding-files-from-deployment), but I did not properly understand the relationship between build step and the zip file creation.  

I also  tried  with two different asset action:  `actions/upload-release-asset@v1` and `svenstaro/upload-release-action@v2`.

You can find my config here: https://github.com/OM4/weatherzone/blob/master/.github/workflows/deploy.yml
And the failed action here: https://github.com/OM4/weatherzone/runs/1066339241?check_suite_focus=true

**Comment by dinhtungdu** [comment]
@om4csaba Can you share the workflow file that you used `actions/upload-release-asset@v1`?

**Comment by the-csaba** [comment]
@dinhtungdu This was that: https://github.com/OM4/weatherzone/blob/7198cce5cda7ff8c34ec17d9ae55873f169e5f1b/.github/workflows/deploy.yml

<details>
  <summary>Content copied here:</summary>

```yaml
name: Deploy to WordPress.org
on:
  release:
    types: [published]
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PLUGINS_GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
```
</details>
