### ISSUE TITLE
README Example issue

### ISSUE THREAD

**Issue by thefrosty** [helen/action-wordpress-plugin-deploy#92]
In the example steps, `uses` and `run` keys aren't allowed in the same step.

```yaml
    - uses: actions/checkout@master
    - name: Build # Remove or modify this step as needed
      run: echo "something" // `run` isn't allowed when `uses` exists in a step...
```

**Comment by jeffpaul** [comment]
@thefrosty I think your copy/paste may have shifted the indentation perhaps?  A quick spot check of the example and one of our existing workflows (https://github.com/10up/retro-winamp-block/blob/develop/.github/workflows/wordpress-plugin-deploy.yml) seems to show that things work as expected.  Perhaps I'm not properly understanding, so if there's more details you can share of what's not working I can dig further?

**Comment by thefrosty** [comment]
Yeah, for sure odd formatting for YML, but in any case I was modifying my deploy action while adding some tests, and came across this error: https://github.com/thefrosty/custom-login/commit/0c8f9629c9008ed10fc6c52cf8055d9f36cdc79c#annotation_3563650310 

```yaml
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        run: |
          echo "GitHub event"
```
